version: '2'
services:
    jobg-app:
        image: jobg
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jobg-mysql:3306/jobg?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jobg-elasticsearch:9300
        ports:
            - 8080:8080
    jobg-mysql:
        extends:
            file: mysql.yml
            service: jobg-mysql
    jobg-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jobg-elasticsearch
